// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/proc.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Code int32

const (
	Code_success Code = 0
	Code_fail    Code = 1
)

var Code_name = map[int32]string{
	0: "success",
	1: "fail",
}

var Code_value = map[string]int32{
	"success": 0,
	"fail":    1,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}

func (Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_29806e2ae0d172cb, []int{0}
}

type Request struct {
	Proc                 []byte   `protobuf:"bytes,1,opt,name=proc,proto3" json:"proc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_29806e2ae0d172cb, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetProc() []byte {
	if m != nil {
		return m.Proc
	}
	return nil
}

type Response struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=protos.Code" json:"code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_29806e2ae0d172cb, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_success
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("protos.Code", Code_name, Code_value)
	proto.RegisterType((*Request)(nil), "protos.request")
	proto.RegisterType((*Response)(nil), "protos.response")
}

func init() {
	proto.RegisterFile("protos/proc.proto", fileDescriptor_29806e2ae0d172cb)
}

var fileDescriptor_29806e2ae0d172cb = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0x28, 0xca, 0x4f, 0xd6, 0x03, 0xb3, 0x85, 0xd8, 0x20, 0x42, 0x4a, 0xb2,
	0x5c, 0xec, 0x45, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x20, 0x05, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0xb6, 0x92, 0x0b, 0x17, 0x47, 0x51, 0x6a, 0x71, 0x41,
	0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x02, 0x17, 0x4b, 0x72, 0x7e, 0x4a, 0x2a, 0x58, 0x9e, 0xcf, 0x88,
	0x07, 0x62, 0x50, 0xb1, 0x1e, 0x48, 0x2c, 0x08, 0x2c, 0x23, 0x24, 0xc6, 0xc5, 0x96, 0x5a, 0x54,
	0xe4, 0x5b, 0x9c, 0x2e, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe5, 0x69, 0xc9, 0x42, 0x74,
	0x0a, 0x71, 0x73, 0xb1, 0x17, 0x97, 0x26, 0x27, 0xa7, 0x16, 0x17, 0x0b, 0x30, 0x08, 0x71, 0x70,
	0xb1, 0xa4, 0x25, 0x66, 0xe6, 0x08, 0x30, 0x3a, 0x71, 0x44, 0x41, 0x5d, 0x93, 0x04, 0xa1, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x03, 0x43, 0xee, 0x6b, 0xb1, 0x00, 0x00, 0x00,
}
